/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jikexueyuan_hellojni_JniBridge */

#ifndef _Included_com_jikexueyuan_hellojni_JniBridge
#define _Included_com_jikexueyuan_hellojni_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jikexueyuan_hellojni_JniBridge
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jikexueyuan_hellojni_JniBridge_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
