/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jikexueyuan_hellondk_GetString */

#ifndef _Included_com_jikexueyuan_hellondk_GetString
#define _Included_com_jikexueyuan_hellondk_GetString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jikexueyuan_hellondk_GetString
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jikexueyuan_hellondk_GetString_getStr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
